services:
  nginx:
    image: nginx:1.27-alpine
    container_name: xtb_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - public_network
      - app_network

  frontend:
    build:
      context: ./xtb-clone-front
      dockerfile: Dockerfile
    container_name: xtb_frontend
    restart: always
    expose:
      - "80"
    depends_on:
      - backend
    networks:
      - app_network

  backend:
    build:
      context: ./Backend/XTBCloneAPI
      dockerfile: Dockerfile
    container_name: xtb_backend
    restart: always
    expose:
      - "8080"
    environment:
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: server=mysql;port=3306;database=xtb_clone_db;user=root;password=root
      JWT_KEY: TO_JEST_BARDZO_DLUGI_SEKRET_DO_JWT_MINIMUM_32_ZNAKI
      FINNHUB_API_KEY: ${FINNHUB_API_KEY}
      Redis__ConnectionString: redis:6379
    volumes:
      - uploads_data:/app/wwwroot/uploads
    depends_on:
      - mysql
      - redis
    networks:
      - app_network
      - data_network

  mysql:
    image: mysql:8.0
    container_name: xtb_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: xtb_clone_db
    expose:
      - "3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - data_network

  redis:
    image: redis:7-alpine
    container_name: xtb_redis
    restart: always
    expose:
      - "6379"
    networks:
      - data_network

volumes:
  mysql_data:
  uploads_data:

networks:
  public_network:
    driver: bridge

  app_network:
    driver: bridge

  data_network:
    driver: bridge
    internal: true